# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megalinks', '0002_link_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tag',
            field=models.CharField(choices=[('MOVIE', 'Movie'), ('GAME', 'Game'), ('TV', 'TV'), ('TUTORIAL', 'Tutorial'), ('MUSIC', 'Music'), ('EBOOK', 'Ebook')], default='', max_length=50),
        ),
    ]
