# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megalinks', '0003_auto_20170303_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tag',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Game', 'Game'), ('TV', 'TV'), ('Tutorial', 'Tutorial'), ('Music', 'Music'), ('Ebook', 'Ebook')], default='', max_length=50),
        ),
    ]
