# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megalinks', '0007_auto_20171107_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tag',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Game', 'Game'), ('TV', 'TV'), ('Tutorial', 'Tutorial'), ('Music', 'Music'), ('Ebook', 'Ebook'), ('Software', 'Software'), ('Documentary', 'Documentary')], default='', max_length=50),
        ),
    ]
